project_name: spotted
version: 2

before:
  hooks:
    - mkdir -p completions
    - sh -c "go run ./cmd/spotted/main.go @completion bash > completions/spotted.bash"
    - sh -c "go run ./cmd/spotted/main.go @completion zsh > completions/spotted.zsh"
    - sh -c "go run ./cmd/spotted/main.go @completion fish > completions/spotted.fish"
    - sh -c "go run ./cmd/spotted/main.go @manpages -o man"

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/spotted/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: '{{ .ProjectName }}'
    main: ./cmd/spotted/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/spotted/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

archives:
  - id: linux-archive
    ids: [linux]
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [tar.gz]
    files:
      - completions/*
      - man/*/*
  - id: macos-archive
    ids: [macos]
    name_template: '{{ .ProjectName }}_{{ .Version }}_macos_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    files:
      - completions/*
      - man/*/*
  - id: windows-archive
    ids: [windows]
    name_template: '{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    files:
      - completions/*
      - man/*/*

snapshot:
  version_template: '{{ .Tag }}-next'

nfpms:
  - license: Apache-2.0
    maintainer: wave@cjav.dev
    bindir: /usr
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    contents:
      - src: man/man1/*.1.gz
        dst: /usr/share/man/man1/
homebrew_casks:
  - name: spotted
    repository:
      owner: cjavdev
      name: homebrew-spotted-cli
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    license: Apache-2.0
    binary: "spotted"
    completions:
      bash: "completions/spotted.bash"
      zsh: "completions/spotted.zsh"
      fish: "completions/spotted.fish"
    manpages:
    - man/man1/spotted.1.gz

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids: [macos]

      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"

      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
